### ISSUE TITLE
GIF support request

### ISSUE THREAD

**Issue by jerrychan7** [itorr/patina#1]
gif？gif。gif！

这么好玩的东西怎么能少了动图？

固定水印，逐帧渲染，计划通√

**Comment by itorr** [comment]
gif 在原理上有些不太适合，本身颜色是依靠色板存储的，无论是加水印还是绿化都会导致画面严重崩坏，在支持之前要先摸索一个可行方案🥺

**Comment by HomeArchbishop** [comment]
可以考虑把gif拆解成jpeg/png，再逐层绿化，然后合成。
我做了一个简单的小样，效果还行。色彩崩坏没看出来🤔
需要优化的就是渲染速度，太慢了🤯。考虑上web worker🙄

**Comment by HomeArchbishop** [comment]
哈哈我收回「没遇到崩坏」这句话🥲
|年份|画质|结果|
|---|---|---|
|原图|原图|![chiya](https://user-images.githubusercontent.com/64010148/181288162-9e4cb6a2-9c34-4f3d-8dec-d6fcd22ca094.GIF)|
|15|76%|![15-76%](https://user-images.githubusercontent.com/64010148/181289160-32a097c2-7f32-48da-a76b-b192f6dd702a.gif)|
|15|16%|![15-16%](https://user-images.githubusercontent.com/64010148/181289232-83cb02a9-2747-456d-8b1f-2a0b119e883d.gif)|
|74|76%|![74-76%](https://user-images.githubusercontent.com/64010148/181289044-321e3258-2e3f-4688-80e2-996fbd07e421.gif)|
|74|8%|![74-8%](https://user-images.githubusercontent.com/64010148/181288183-dc1680c1-6b18-41e5-b798-b29c90d5438d.gif)|

不知道这个包浆效果是好是坏了🤯

只有熊猫头这种没色彩的挺好，就是像素太低了，水印看不清。(◐‿◑)﻿

> 话说其实静态图片这样搞也是一样的效果，那gif可能就不算崩溃了吧（捂脸
> ![70-2%-static](https://user-images.githubusercontent.com/64010148/181292741-c396e4ad-3c09-458e-83b8-3b04ef048d2b.jpeg)

**Comment by itorr** [comment]
TAT 写着回复发现有了新进展 重头来ψ(｀∇´)ψ

主要麻烦的地方在于 jpeg 的波纹痕迹和水印会带来大量的杂色，gif 色板看到直摇头🤕
gif 我记得是可以支持区域色板的，倒是也可以牺牲文件大小 换回一定的画质😟
在色板不变的情况下 也可以适当的给图像增加抖动，也可以让整体的信息保留更多

**Comment by itorr** [comment]
其实画质超低时色板数反倒直线下降，特别适合 gif 了🤣

**Comment by itorr** [comment]
咦，好像现在的样例已经是用了区域色板的图像了🤔 作为输出结果来说我觉得是完全可用的

**Comment by HomeArchbishop** [comment]
那如果不是区域色板，也没法转换啊😔
看来失真是不可避免了

诶，生成的图片也是区域色板吗(◐‿◑)﻿

**Comment by itorr** [comment]
> 那如果不是区域色板，也没法转换啊😔 看来失真是不可避免了
> 
> 诶，生成的图片也是区域色板吗(◐‿◑)

其实现在的样例看起来已经是可用的了，有些 gif 特有的劣化其实也很契合这个项目来着。原本的劣化就包含 jpeg 的压缩来着👻

**Comment by HomeArchbishop** [comment]
~~确实，这么垃圾的画质更像包浆。。。(◐‿◑)﻿~~

我整理整理，看看发个草稿 pull request。我是单独放了一个文件，没有在 `patina.js` 里增改。

（ 你说未来要解耦来着，未来你有空解耦好了我再 pull request 也可以( ´▽｀) ）

**Comment by itorr** [comment]
#7 以支持
