### ISSUE TITLE
特殊 GIF 图片会导致输出图像出错

### ISSUE THREAD

**Issue by itorr** [itorr/patina#9]
![5](https://user-images.githubusercontent.com/1933673/183223719-3cb2d5ac-a0e0-473e-80ff-dd39f793c8a2.gif)

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1933673/183223765-b19c80e6-8a78-49d7-b47a-9deb42af8ec1.png">

**Comment by HomeArchbishop** [comment]
啊这，好意外的bug。有搞清楚是什么原因吗 (._.)

**Comment by itorr** [comment]
🤯奇怪自己提的 issue 居然没有消息推送
居然会是这个原因🤔️

**Comment by HomeArchbishop** [comment]
是我大意了。

图片尺寸太大的时候，会自动缩放到 maxWidth（500px）。然而每次迭代的时候，用的是原图的尺寸获取图片，即：试图在 500px 的 imgEl 上获取 1400px 的信息，再绘制到 canvas 上，当然会有一大片空白啦！🌝

**Comment by itorr** [comment]
不过这么大的动图本身也很离谱🤯
